# Generated by Django 5.2.12 on 2026-03-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='work_hour',
            field=models.CharField(max_length=200),
        ),
    ]
